/** @typedef {import('./AST').ASTNode} ASTNode */
/** @typedef {import('./utils').BBScriptFuncMap} BBScriptFuncMap */
import { isStopError, runOptions } from "../scope";

/**
 * @typedef {Object} BBScriptOptions
 * @property {string} callerId
 * @property {string} callerClass
 * @property {Object<string, any>} data the post's variables, shared only by that post's scripts
 * @property {BBScriptProcessor} processor
 * @property {Element | NodeListOf<Element>} target
 * @property {Element} root the post element; selectors never reach outside it
 * @property {Set<number>} timers the post's timer handles, cleared when it goes away
 */

export class BBScriptProcessor {
  /** @type {BBScriptOptions} */
  options;
  /** @type {BBScriptFuncMap} */
  functions;

  /**
   * @param {BBScriptFuncMap} functions
   * @param {BBScriptOptions} [defaultOptions={} as BBScriptOptions]
   */
  constructor(functions, defaultOptions = {}) {
    defaultOptions = {
      ...defaultOptions,
      processor: this,
    };
    this.options = defaultOptions;
    this.functions = functions;
  }
  /**
   * Processes and executes all commands in node tree
   * @param {ASTNode[]} nodeTree input node tree, generated by `parse()`
   * @param {string} callerId
   * @param {string} callerClass
   * @param {BBScriptOptions} [options=this.options] options to use
   * @returns {void}
   */
  execAll(nodeTree, callerId, callerClass, options = this.options) {
    options = runOptions(this.options, options, callerId, callerClass);
    if (!options) {
      return;
    }
    try {
      for (const node of nodeTree) {
        node.resolveValue(options);
      }
    } catch (error) {
      if (!isStopError(error)) {
        throw error;
      }
    }
  }
}
