plugins:
  bbcode_enabled:
    default: true
    client: true
  enable_markdown_typographer:
    client: false
    default: false
  markdown_typographer_quotation_marks:
    client: false
    default: false
  discourse_normalize_whitespace:
    default: false
    client: true
    description:
      en: "Activate to set all whitespace to the default space character (U+0020)"
  preserve_whitespace:
    default: true
    client: true
    description:
      en: "Activate to set repeating spaces (U+0020) to non-breaking spaces (U+00A0).
      Note that discourse_normalize_whitespace must be disabled to preserve non-breaking spaces."
  enable_bbscript:
    default: true
    client: true
    description:
      en: "Activate to enable BBScript support. See the github wiki for more information."
  enable_bbcode_error_reporting:
    default: true
    client: true
    description:
      en: "Activate to enable BBCode error reporting. This will display a message in the composer window if there is an error in the BBCode."
