# frozen_string_literal: true

# The cooking baseline. Each spec/fixtures/recook/<group>.txt holds raw posts,
# each after a "==== <name>" line; <group>.cooked holds their HTML as last
# recorded, in the same format. Any change to any case fails here. When the
# change is intended, rewrite the snapshots with
#   UPDATE_RECOOK=1 LOAD_PLUGINS=1 bin/rspec plugins/bbcode/spec/lib/recook_spec.rb
# and review the .cooked diff. The tag-*.txt groups are generated by
# spec/fixtures/recook/generate.rb; edit that, not them.
#
# The same run writes test/javascripts/recook-corpus.js: each case with the
# markdown engine's HTML before the server's cleanup, and the settings the
# server gave the engine, which the composer test (bbcode-recook-test.js)
# cooks with and must match. Only its cases are checked here, so a change to
# core's settings alone doesn't fail this spec.
RSpec.describe PrettyText do
  before do
    SiteSetting.bbcode_enabled = true
    PrettyText.reset_context
  end

  after { PrettyText.reset_context }

  let(:fixtures) { File.expand_path("../fixtures/recook", __dir__) }
  let(:corpus_path) { File.expand_path("../../test/javascripts/recook-corpus.js", __dir__) }

  # the per-post id is random
  def normalize(html)
    html.gsub(/post-[a-z0-9]{5}/, "post-GUID")
  end

  # [cooked as a post is, [comment]s included; the engine's HTML]
  def cook(raw)
    html = PrettyText.markdown(raw)
    [normalize(BbCode::Comments.restore(PrettyText.cleanup(html))), normalize(html)]
  end

  # text before the first case is a comment
  def read_cases(path)
    _comment, *pairs = File.read(path).split(/^==== (.+)\n/, -1)
    pairs.each_slice(2).to_h { |name, text| [name, text.delete_suffix("\n")] }
  end

  def write_cases(path, cases)
    File.write(path, cases.map { |name, text| "==== #{name}\n#{text}\n" }.join)
  end

  def corpus_js(cases)
    settings = {
      siteSettings: SiteSetting.client_settings_hash,
      additionalOptions: Site.markdown_additional_options,
    }
    "// Generated by spec/lib/recook_spec.rb with UPDATE_RECOOK=1; don't edit.\n" \
      "export const options = #{JSON.generate(settings)};\n" \
      "// cases\n" \
      "// { group: { case: [raw, the markdown engine's HTML] } }\n" \
      "export default #{JSON.pretty_generate(cases)};\n"
  end

  # the module without its options, which only a settings change alters
  def corpus_cases(text)
    text && text[text.index("// cases\n").to_i..]
  end

  it "cooks every bbcode case as its recook snapshot" do
    groups = Dir[File.join(fixtures, "*.txt")].sort
    expect(groups).not_to be_empty

    changed = []
    corpus = {}
    groups.each do |input|
      group = File.basename(input, ".txt")
      raws = read_cases(input)
      results = raws.transform_values { |raw| cook(raw) }
      corpus[group] = raws.to_h { |name, raw| [name, [raw, results[name][1]]] }
      cooked = results.transform_values(&:first)
      snapshot = input.delete_suffix(".txt") + ".cooked"
      if ENV["UPDATE_RECOOK"]
        write_cases(snapshot, cooked)
        next
      end

      expected = File.exist?(snapshot) ? read_cases(snapshot) : {}
      (cooked.keys | expected.keys).each do |name|
        changed << "#{group}/#{name}" if cooked[name] != expected[name]
      end
    end

    if ENV["UPDATE_RECOOK"]
      File.write(corpus_path, corpus_js(corpus))
    elsif corpus_cases(File.exist?(corpus_path) ? File.read(corpus_path) : nil) !=
          corpus_cases(corpus_js(corpus))
      changed << "test/javascripts/recook-corpus.js"
    end

    expect(changed).to be_empty,
    "#{changed.size} cases cooked differently from their snapshot: " \
      "#{changed.first(30).join(", ")}#{changed.size > 30 ? ", ..." : ""}. " \
      "If intended, rerun with UPDATE_RECOOK=1 and review the diff."
  end
end
